server:
  port: 8080
  servlet:
    context-path: /cellphonesite
spring:
  datasource:
    password: 12345
    url: jdbc:mysql://localhost:3306/cellphonesite
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true